/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define min_val_GranularityPeriod_KPMv2 (1)
#define max_val_GranularityPeriod_KPMv2 (4294967295)
#define min_val_SubscriptionID_KPMv2 (1)
#define max_val_SubscriptionID_KPMv2 (4294967295)
#define min_val_GNB_CU_UP_ID_KPMv2 (0)
#define max_val_GNB_CU_UP_ID_KPMv2 (68719476735)
#define min_val_GNB_DU_ID_KPMv2 (0)
#define max_val_GNB_DU_ID_KPMv2 (68719476735)
#define maxnoofKPMNodes_KPMv2 (1024)
#define maxnoofCells_KPMv2 (16384)
#define maxnoofRICStyles_KPMv2 (63)
#define maxnoofMeasurementInfo_KPMv2 (65535)
#define maxnoofLabelInfo_KPMv2 (2147483647)
#define maxnoofMeasurementRecord_KPMv2 (65535)
#define maxnoofMeasurementValue_KPMv2 (2147483647)
#define maxnoofConditionInfo_KPMv2 (32768)
#define maxnoofUEID_KPMv2 (65535)
#define min_val_GNB_CU_UP_ID (0)
#define max_val_GNB_CU_UP_ID (68719476735)
#define min_val_GNB_DU_ID (0)
#define max_val_GNB_DU_ID (68719476735)
#define min_val_NGENB_DU_ID (0)
#define max_val_NGENB_DU_ID (68719476735)
#define min_val_RANfunctionID (0)
#define max_val_RANfunctionID (4095)
#define min_val_RANfunctionRevision (0)
#define max_val_RANfunctionRevision (4095)
#define min_val_RICactionID (0)
#define max_val_RICactionID (255)
#define min_val_RICindicationSN (0)
#define max_val_RICindicationSN (65535)
#define min_val_ProcedureCode (0)
#define max_val_ProcedureCode (255)
#define min_val_ProtocolIE_ID (0)
#define max_val_ProtocolIE_ID (65535)
#define maxProtocolIEs (65535)
#define maxnoofErrors (256)
#define maxofE2nodeComponents (1024)
#define maxofRANfunctionID (256)
#define maxofRICactionID (16)
#define maxofTNLA (32)
#define maxofRICrequestID (4294967295)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
