/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "asn1/e2sm_v3.00.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -fincludes-quoted -D src`
 */

#ifndef	_Beam_ID_H_
#define	_Beam_ID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NR-SSB-Index.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Beam_ID_PR {
	Beam_ID_PR_NOTHING,	/* No components present */
	Beam_ID_PR_nR_Beam_ID
	/* Extensions may appear below */
	
} Beam_ID_PR;

/* Beam-ID */
typedef struct Beam_ID {
	Beam_ID_PR present;
	union Beam_ID_u {
		NR_SSB_Index_t	 nR_Beam_ID;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Beam_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Beam_ID;

#ifdef __cplusplus
}
#endif

#endif	/* _Beam_ID_H_ */
#include "asn_internal.h"
