/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "asn1/e2sm_v3.00.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -fincludes-quoted -D src`
 */

#include "Cell-RNTI.h"

asn_TYPE_member_t asn_MBR_Cell_RNTI_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Cell_RNTI, c_RNTI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RNTI_Value,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"c-RNTI"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Cell_RNTI, cell_Global_ID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CGI,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"cell-Global-ID"
		},
};
static const ber_tlv_tag_t asn_DEF_Cell_RNTI_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Cell_RNTI_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* c-RNTI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cell-Global-ID */
};
asn_SEQUENCE_specifics_t asn_SPC_Cell_RNTI_specs_1 = {
	sizeof(struct Cell_RNTI),
	offsetof(struct Cell_RNTI, _asn_ctx),
	asn_MAP_Cell_RNTI_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Cell_RNTI = {
	"Cell-RNTI",
	"Cell-RNTI",
	&asn_OP_SEQUENCE,
	asn_DEF_Cell_RNTI_tags_1,
	sizeof(asn_DEF_Cell_RNTI_tags_1)
		/sizeof(asn_DEF_Cell_RNTI_tags_1[0]), /* 1 */
	asn_DEF_Cell_RNTI_tags_1,	/* Same as above */
	sizeof(asn_DEF_Cell_RNTI_tags_1)
		/sizeof(asn_DEF_Cell_RNTI_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_Cell_RNTI_1,
	2,	/* Elements count */
	&asn_SPC_Cell_RNTI_specs_1	/* Additional specs */
};

