/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "asn1/e2sm_v3.00.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -fincludes-quoted -D src`
 */

#ifndef	_ENB_UE_X2AP_ID_Extension_H_
#define	_ENB_UE_X2AP_ID_Extension_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ENB-UE-X2AP-ID-Extension */
typedef long	 ENB_UE_X2AP_ID_Extension_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ENB_UE_X2AP_ID_Extension_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ENB_UE_X2AP_ID_Extension;
asn_struct_free_f ENB_UE_X2AP_ID_Extension_free;
asn_struct_print_f ENB_UE_X2AP_ID_Extension_print;
asn_constr_check_f ENB_UE_X2AP_ID_Extension_constraint;
xer_type_decoder_f ENB_UE_X2AP_ID_Extension_decode_xer;
xer_type_encoder_f ENB_UE_X2AP_ID_Extension_encode_xer;
per_type_decoder_f ENB_UE_X2AP_ID_Extension_decode_uper;
per_type_encoder_f ENB_UE_X2AP_ID_Extension_encode_uper;
per_type_decoder_f ENB_UE_X2AP_ID_Extension_decode_aper;
per_type_encoder_f ENB_UE_X2AP_ID_Extension_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ENB_UE_X2AP_ID_Extension_H_ */
#include "asn_internal.h"
