/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "asn1/e2sm_kpm_v2.0.03.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -fincludes-quoted -D src`
 */

#ifndef	_GranularityPeriod_H_
#define	_GranularityPeriod_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GranularityPeriod */
typedef unsigned long	 GranularityPeriod_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GranularityPeriod_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GranularityPeriod;
extern const asn_INTEGER_specifics_t asn_SPC_GranularityPeriod_specs_1;
asn_struct_free_f GranularityPeriod_free;
asn_struct_print_f GranularityPeriod_print;
asn_constr_check_f GranularityPeriod_constraint;
xer_type_decoder_f GranularityPeriod_decode_xer;
xer_type_encoder_f GranularityPeriod_encode_xer;
per_type_decoder_f GranularityPeriod_decode_uper;
per_type_encoder_f GranularityPeriod_encode_uper;
per_type_decoder_f GranularityPeriod_decode_aper;
per_type_encoder_f GranularityPeriod_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _GranularityPeriod_H_ */
#include "asn_internal.h"
