/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "asn1/e2sm_v3.00.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -fincludes-quoted -D src`
 */

#ifndef	_PartialUEID_H_
#define	_PartialUEID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "AMF-UE-NGAP-ID.h"
#include "GNB-CU-UE-F1AP-ID.h"
#include "GNB-CU-CP-UE-E1AP-ID.h"
#include "RANUEID.h"
#include "NG-RANnodeUEXnAPID.h"
#include "NGENB-CU-UE-W1AP-ID.h"
#include "ENB-UE-X2AP-ID.h"
#include "ENB-UE-X2AP-ID-Extension.h"
#include "MME-UE-S1AP-ID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GUAMI;
struct GlobalNGRANNodeID;
struct Cell_RNTI;
struct GlobalENB_ID;
struct GUMMEI;

/* PartialUEID */
typedef struct PartialUEID {
	AMF_UE_NGAP_ID_t	*amf_UE_NGAP_ID;	/* OPTIONAL */
	struct GUAMI	*guami;	/* OPTIONAL */
	GNB_CU_UE_F1AP_ID_t	*gNB_CU_UE_F1AP_ID;	/* OPTIONAL */
	GNB_CU_CP_UE_E1AP_ID_t	*gNB_CU_CP_UE_E1AP_ID;	/* OPTIONAL */
	RANUEID_t	*ran_UEID;	/* OPTIONAL */
	NG_RANnodeUEXnAPID_t	*m_NG_RAN_UE_XnAP_ID;	/* OPTIONAL */
	struct GlobalNGRANNodeID	*globalNG_RANNode_ID;	/* OPTIONAL */
	struct Cell_RNTI	*cell_RNTI;	/* OPTIONAL */
	NGENB_CU_UE_W1AP_ID_t	*ng_eNB_CU_UE_W1AP_ID;	/* OPTIONAL */
	ENB_UE_X2AP_ID_t	*m_eNB_UE_X2AP_ID;	/* OPTIONAL */
	ENB_UE_X2AP_ID_Extension_t	*m_eNB_UE_X2AP_ID_Extension;	/* OPTIONAL */
	struct GlobalENB_ID	*globalENB_ID;	/* OPTIONAL */
	MME_UE_S1AP_ID_t	*mME_UE_S1AP_ID;	/* OPTIONAL */
	struct GUMMEI	*gUMMEI;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PartialUEID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PartialUEID;

#ifdef __cplusplus
}
#endif

#endif	/* _PartialUEID_H_ */
#include "asn_internal.h"
