/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "asn1/e2sm_kpm_v2.0.3-changed.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -fincludes-quoted -D src`
 */

#include "RIC-KPMNode-Item-KPMv2.h"

#include "Cell-Measurement-Object-Item-KPMv2.h"
static int
memb_cell_Measurement_Object_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1UL && size <= 16384UL)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_cell_Measurement_Object_List_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 14,  14,  1,  16384 }	/* (SIZE(1..16384)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_cell_Measurement_Object_List_constr_3 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 14,  14,  1,  16384 }	/* (SIZE(1..16384)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static asn_TYPE_member_t asn_MBR_cell_Measurement_Object_List_3[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Cell_Measurement_Object_Item_KPMv2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_cell_Measurement_Object_List_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_cell_Measurement_Object_List_specs_3 = {
	sizeof(struct RIC_KPMNode_Item_KPMv2__cell_Measurement_Object_List),
	offsetof(struct RIC_KPMNode_Item_KPMv2__cell_Measurement_Object_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_cell_Measurement_Object_List_3 = {
	"cell-Measurement-Object-List",
	"cell-Measurement-Object-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_cell_Measurement_Object_List_tags_3,
	sizeof(asn_DEF_cell_Measurement_Object_List_tags_3)
		/sizeof(asn_DEF_cell_Measurement_Object_List_tags_3[0]) - 1, /* 1 */
	asn_DEF_cell_Measurement_Object_List_tags_3,	/* Same as above */
	sizeof(asn_DEF_cell_Measurement_Object_List_tags_3)
		/sizeof(asn_DEF_cell_Measurement_Object_List_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_cell_Measurement_Object_List_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_cell_Measurement_Object_List_3,
	1,	/* Single element */
	&asn_SPC_cell_Measurement_Object_List_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RIC_KPMNode_Item_KPMv2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RIC_KPMNode_Item_KPMv2, ric_KPMNode_Type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_GlobalKPMnode_ID_KPMv2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"ric-KPMNode-Type"
		},
	{ ATF_POINTER, 1, offsetof(struct RIC_KPMNode_Item_KPMv2, cell_Measurement_Object_List),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_cell_Measurement_Object_List_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_cell_Measurement_Object_List_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
			memb_cell_Measurement_Object_List_constraint_1
		},
		0, 0, /* No default value */
		"cell-Measurement-Object-List"
		},
};
static const int asn_MAP_RIC_KPMNode_Item_KPMv2_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_RIC_KPMNode_Item_KPMv2_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RIC_KPMNode_Item_KPMv2_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-KPMNode-Type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* cell-Measurement-Object-List */
};
asn_SEQUENCE_specifics_t asn_SPC_RIC_KPMNode_Item_KPMv2_specs_1 = {
	sizeof(struct RIC_KPMNode_Item_KPMv2),
	offsetof(struct RIC_KPMNode_Item_KPMv2, _asn_ctx),
	asn_MAP_RIC_KPMNode_Item_KPMv2_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_RIC_KPMNode_Item_KPMv2_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RIC_KPMNode_Item_KPMv2 = {
	"RIC-KPMNode-Item-KPMv2",
	"RIC-KPMNode-Item-KPMv2",
	&asn_OP_SEQUENCE,
	asn_DEF_RIC_KPMNode_Item_KPMv2_tags_1,
	sizeof(asn_DEF_RIC_KPMNode_Item_KPMv2_tags_1)
		/sizeof(asn_DEF_RIC_KPMNode_Item_KPMv2_tags_1[0]), /* 1 */
	asn_DEF_RIC_KPMNode_Item_KPMv2_tags_1,	/* Same as above */
	sizeof(asn_DEF_RIC_KPMNode_Item_KPMv2_tags_1)
		/sizeof(asn_DEF_RIC_KPMNode_Item_KPMv2_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_RIC_KPMNode_Item_KPMv2_1,
	2,	/* Elements count */
	&asn_SPC_RIC_KPMNode_Item_KPMv2_specs_1	/* Additional specs */
};

