/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "asn1/e2sm_v3.00.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -fincludes-quoted -D src`
 */

#ifndef	_RIC_Style_Type_H_
#define	_RIC_Style_Type_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* RIC-Style-Type */
typedef long	 RIC_Style_Type_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RIC_Style_Type;
asn_struct_free_f RIC_Style_Type_free;
asn_struct_print_f RIC_Style_Type_print;
asn_constr_check_f RIC_Style_Type_constraint;
xer_type_decoder_f RIC_Style_Type_decode_xer;
xer_type_encoder_f RIC_Style_Type_encode_xer;
per_type_decoder_f RIC_Style_Type_decode_uper;
per_type_encoder_f RIC_Style_Type_encode_uper;
per_type_decoder_f RIC_Style_Type_decode_aper;
per_type_encoder_f RIC_Style_Type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RIC_Style_Type_H_ */
#include "asn_internal.h"
