/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "asn1/e2sm_v3.00.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -fincludes-quoted -D src`
 */

#ifndef	_SubscriberProfileIDforRFP_H_
#define	_SubscriberProfileIDforRFP_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SubscriberProfileIDforRFP */
typedef long	 SubscriberProfileIDforRFP_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SubscriberProfileIDforRFP;
asn_struct_free_f SubscriberProfileIDforRFP_free;
asn_struct_print_f SubscriberProfileIDforRFP_print;
asn_constr_check_f SubscriberProfileIDforRFP_constraint;
xer_type_decoder_f SubscriberProfileIDforRFP_decode_xer;
xer_type_encoder_f SubscriberProfileIDforRFP_encode_xer;
per_type_decoder_f SubscriberProfileIDforRFP_decode_uper;
per_type_encoder_f SubscriberProfileIDforRFP_encode_uper;
per_type_decoder_f SubscriberProfileIDforRFP_decode_aper;
per_type_encoder_f SubscriberProfileIDforRFP_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SubscriberProfileIDforRFP_H_ */
#include "asn_internal.h"
