/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "asn1/e2sm_kpm_v2.0.3-changed.asn"
 * 	`asn1c -gen-APER -gen-UPER -no-gen-JER -no-gen-BER -no-gen-OER -fcompound-names -no-gen-example -findirect-choice -fno-include-deps -fincludes-quoted -D src`
 */

#ifndef	_UE_Identity_KPMv2_H_
#define	_UE_Identity_KPMv2_H_


#include "asn_application.h"

/* Including external dependencies */
#include "OCTET_STRING.h"

#ifdef __cplusplus
extern "C" {
#endif

/* UE-Identity-KPMv2 */
typedef OCTET_STRING_t	 UE_Identity_KPMv2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UE_Identity_KPMv2;
asn_struct_free_f UE_Identity_KPMv2_free;
asn_struct_print_f UE_Identity_KPMv2_print;
asn_constr_check_f UE_Identity_KPMv2_constraint;
xer_type_decoder_f UE_Identity_KPMv2_decode_xer;
xer_type_encoder_f UE_Identity_KPMv2_encode_xer;
per_type_decoder_f UE_Identity_KPMv2_decode_uper;
per_type_encoder_f UE_Identity_KPMv2_encode_uper;
per_type_decoder_f UE_Identity_KPMv2_decode_aper;
per_type_encoder_f UE_Identity_KPMv2_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _UE_Identity_KPMv2_H_ */
#include "asn_internal.h"
