# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secsm/rpc/protos/mobiflow_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'secsm/rpc/protos/mobiflow_service.proto\"4\n\x15MobiFlowStreamRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\")\n\x16MobiFlowStreamResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2T\n\rMobiFlowQuery\x12\x43\n\x0eMobiFlowStream\x12\x16.MobiFlowStreamRequest\x1a\x17.MobiFlowStreamResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secsm.rpc.protos.mobiflow_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MOBIFLOWSTREAMREQUEST']._serialized_start=43
  _globals['_MOBIFLOWSTREAMREQUEST']._serialized_end=95
  _globals['_MOBIFLOWSTREAMRESPONSE']._serialized_start=97
  _globals['_MOBIFLOWSTREAMRESPONSE']._serialized_end=138
  _globals['_MOBIFLOWQUERY']._serialized_start=140
  _globals['_MOBIFLOWQUERY']._serialized_end=224
# @@protoc_insertion_point(module_scope)
