# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: secsm/server/protos/mobiflow_service.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*secsm/server/protos/mobiflow_service.proto\"3\n\x14MobiFlowQueryRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05table\x18\x02 \x01(\t\"(\n\x15MobiFlowQueryResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2Q\n\rMobiFlowQuery\x12@\n\rMobiFlowQuery\x12\x15.MobiFlowQueryRequest\x1a\x16.MobiFlowQueryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'secsm.server.protos.mobiflow_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MOBIFLOWQUERYREQUEST']._serialized_start=46
  _globals['_MOBIFLOWQUERYREQUEST']._serialized_end=97
  _globals['_MOBIFLOWQUERYRESPONSE']._serialized_start=99
  _globals['_MOBIFLOWQUERYRESPONSE']._serialized_end=139
  _globals['_MOBIFLOWQUERY']._serialized_start=141
  _globals['_MOBIFLOWQUERY']._serialized_end=222
# @@protoc_insertion_point(module_scope)
