# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from secsm.rpc.protos import mobiflow_service_pb2 as secsm_dot_rpc_dot_protos_dot_mobiflow__service__pb2


class MobiFlowQueryStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MobiFlowStream = channel.unary_stream(
                '/MobiFlowQuery/MobiFlowStream',
                request_serializer=secsm_dot_rpc_dot_protos_dot_mobiflow__service__pb2.MobiFlowStreamRequest.SerializeToString,
                response_deserializer=secsm_dot_rpc_dot_protos_dot_mobiflow__service__pb2.MobiFlowStreamResponse.FromString,
                )


class MobiFlowQueryServicer(object):
    """The service definition.
    """

    def MobiFlowStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MobiFlowQueryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MobiFlowStream': grpc.unary_stream_rpc_method_handler(
                    servicer.MobiFlowStream,
                    request_deserializer=secsm_dot_rpc_dot_protos_dot_mobiflow__service__pb2.MobiFlowStreamRequest.FromString,
                    response_serializer=secsm_dot_rpc_dot_protos_dot_mobiflow__service__pb2.MobiFlowStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MobiFlowQuery', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MobiFlowQuery(object):
    """The service definition.
    """

    @staticmethod
    def MobiFlowStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/MobiFlowQuery/MobiFlowStream',
            secsm_dot_rpc_dot_protos_dot_mobiflow__service__pb2.MobiFlowStreamRequest.SerializeToString,
            secsm_dot_rpc_dot_protos_dot_mobiflow__service__pb2.MobiFlowStreamResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
